### ISSUE TITLE
Creation of an Azure Subscription and/or ressource group

### ISSUE THREAD

**Issue by JRBC** [nexi-intra/msnordics-supplychainpoc#1]
Hi,

As a developer I need azure subscription or resource group 
to deploy azure components to run the application on/against.

The intended components (not all necessarily required and probably not all included):
- Azure Data Factory
- Azure SQL Server and/or Azure Managed SQL
- Azure Storage Account -> Azure Data Lake Gen2
- Azure Key Vault

Kind regards,
Johnny

**Comment by JRBC** [comment]
@ngjoh, any updates on this issue

**Comment by JohnnyRasmussenNexi** [comment]
Subscription was made but user admin-johra@nets.eu still not working - will close and reopen a new issue on this
