### ISSUE TITLE
PowerBI/Fabric Workspace

### ISSUE THREAD

**Issue by JRBC** [nexi-intra/msnordics-supplychainpoc#2]
Hi,

As a developer I need a PowerBI/fabric workspace
So I can develop and deploy items for my users

The workspace should be named "SupplyChainPoC" and Rasmus Kjærulf and I should be the initial owners/admins

Kind regards,
Johnny

**Comment by JRBC** [comment]
If the https://github.com/nexi-intra/msnordics-supplychainpoc/issues/4 has been resolved.
Please add the SupplyChainDWAdm group as the admins of this workspace

**Comment by JRBC** [comment]
@ngjoh, any updates on this issue

**Comment by JohnnyRasmussenNexi** [comment]
Workspace created and hereby closing
