### ISSUE TITLE
Create Fabric Items Permission

### ISSUE THREAD

**Issue by JRBC** [nexi-intra/msnordics-supplychainpoc#3]
Hi,

As a developer I need the correct permissions to create fabric items so I can create some of these elements:
- Copy job
- Pipelines
- Dataflows gen1/gen2
- Notebook
- Lake Houses
- Data Warehouses
- Datamart
- Azure Data Factory 

To create the Supply Chain Data Warehouse.

This is done on PowerBI/Fabric Admin Portal:
![Image](https://github.com/user-attachments/assets/892cde30-6e04-48ef-bee8-bde6d3134f78)

**Comment by JRBC** [comment]
If https://github.com/nexi-intra/msnordics-supplychainpoc/issues/4 has been resolved
I suggest that only users in the SupplyChainDWMember and SupplyChainDWAdm is given this permission.

**Comment by JohnnyRasmussenNexi** [comment]
Issue closed
