### ISSUE TITLE
EntraID Security User Groups

### ISSUE THREAD

**Issue by JRBC** [nexi-intra/msnordics-supplychainpoc#4]
As a business application owner 
I need Entra ID Security groups 
to effectively handle the access management of the applications.

I need to have the following groups created:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JOHNNY~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JOHNNY~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Group Type | Group Name | Group Description | Role Assignment | Membership type | Owner | Memebers
-- | -- | -- | -- | -- | -- | --
Security | SupplyChainDWAdm | This group has admin rights over the Supply Chain workspace(s) | No | Assigned | Rasmus Kjærulf | Johnny Rasmussen
Security | SupplyChainDWMember | This group is used for developers and can delete/create lake houses and   data warehouses | No | Assigned | Rasmus Kjærulf | Johnny Rasmussen
Security | SupplyChainDWContributor | This group is used for super users - who can work on pipelines etc | No | Assigned | Rasmus Kjærulf | Rasmus Kjærulf
Security | SupplyChainDWViewer | This group has viewing rights on the elements in the workspace | No | Assigned | Rasmus Kjærulf | Rasmus Kjærulf

</body>

</html>
 
Kind regards,
Johnny

**Comment by JRBC** [comment]
@ngjoh, any updates on this issue

**Comment by JohnnyRasmussenNexi** [comment]
Marked as closed
A separate subscription with a separate capacity was made
